### ISSUE TITLE
Cast exception when nested schema passed as input

### ISSUE THREAD

**Issue by pramodbiligiri** [databrickslabs/dbldatagen#135]
## Expected Behavior
Nested Schema shown below should be processed correctly

## Current Behavior
Cast exception is thrown as follows:
```
PySpark version: 3.3.1
PySpark SparkContext version: 3.3.1
StructType([StructField('id', LongType(), True), StructField('city', StructType([StructField('id', LongType(), True), StructField('population', LongType(), True)]), True)])
Traceback (most recent call last):
  File "nested-schema.py", line 24, in <module>
    res1 = gen1.build(withTempView=True)
  File "/home/pramod/.local/lib/python3.8/site-packages/dbldatagen/data_generator.py", line 925, in build
    df1 = self._buildColumnExpressionsWithSelects(df1)
  File "/home/pramod/.local/lib/python3.8/site-packages/dbldatagen/data_generator.py", line 972, in _buildColumnExpressionsWithSelects
    df1 = df1.select(*build_round)
  File "/home/pramod/.local/lib/python3.8/site-packages/pyspark/sql/dataframe.py", line 2023, in select
    jdf = self._jdf.select(self._jcols(*cols))
  File "/home/pramod/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1321, in __call__
    return_value = get_return_value(
  File "/home/pramod/.local/lib/python3.8/site-packages/pyspark/sql/utils.py", line 196, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: cannot resolve '(id + CAST(0 AS BIGINT))' due to data type mismatch: cannot cast bigint to struct<id:bigint,population:bigint>;
'Project [id#0L, cast(cast((id#0L + cast(0 as bigint)) as struct<id:bigint,population:bigint>) as struct<id:bigint,population:bigint>) AS city#2]
+- Range (0, 10, step=1, splits=Some(2))
```

## Steps to Reproduce (for bugs)
Code below is run as $python3.8 nested_schema.py
Pyspark version is 3.3.1

```
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, IntegerType, StringType, LongType, DoubleType
import dbldatagen as datagen

spark = SparkSession.builder \
    .master("local[4]") \
    .appName("Nested Schema") \
    .getOrCreate()

print('PySpark version: ' + spark.version)
print('PySpark SparkContext version: ' + spark.sparkContext.version)

struct_type = StructType([
                StructField('id', LongType(), True),
                StructField("city", StructType([
                    StructField('id', LongType(), True),
                    StructField('population', LongType(), True)
                ]), True)])

print(struct_type)

gen1 = datagen.DataGenerator(sparkSession=spark, name="nested_schema", rows=10, partitions=2) \
      .withSchema(struct_type).withColumn("id")
res1 = gen1.build(withTempView=True)
res1.show(res1.count())
```
## Your Environment

* `dbldatagen` version used: python3.8 -m pip install https://github.com/databrickslabs/dbldatagen/releases/download/release%2Fv0.2.1/dbldatagen-0.2.1-py3-none-any.whl
* Databricks Runtime version: N/A
* Cloud environment used: Local laptop

**Comment by pramodbiligiri** [comment]
I'm able to generate the "city" struct above by hardcoding an equivalent SQL expression in its ColumnSpec. Not a particular useful way in the larger scheme of things :(

```
gen1 = dbl.DataGenerator(debug=True, verbose=True, sparkSession=spark, name="nested_schema",
                         rows=10, partitions=2) \
       .withSchema(struct_type) \
       .withColumnSpec("city",
                       structType='struct',
                       expr='named_struct("id", rand(), "population", rand())',
                       baseColumn="id")

print(gen1.schema)
print(gen1.describe())
print(gen1.explain())

res1 = gen1.build(withTempView=True)
res1.show(res1.count())
```

**Comment by ronanstokes-db** [comment]
Thanks for your feedback - i'll investigate

**Comment by giulioungaretti** [comment]
@ronanstokes-db , I can repro without id too :D 

<img width="1220" alt="Screenshot 2022-12-21 at 16 38 46" src="https://user-images.githubusercontent.com/2694199/208943927-8007f510-76fe-43b8-b56d-1d538f1ab18a.png">

**Comment by giulioungaretti** [comment]
🙋‍♀️ @ronanstokes-db , I can repro without any ids, and in general with any nested schema!
e.g. 
<img width="1181" alt="Screenshot 2022-12-21 at 16 39 50" src="https://user-images.githubusercontent.com/2694199/208944191-02235a43-c7f4-437b-94ae-d698ec0781e0.png">

**Comment by ronanstokes-db** [comment]
Thanks for the update - will look into this

**Comment by ronanstokes-db** [comment]
There's a couple of things to note in your example:

1 - `withColumn` introduces a new field, `withColumnSpec` controls the generation of data for an existing field - so when you use `withColumn` to introduce a new field called `id`, you're introducing a new field called `id` that conflicts with an existing one.

2 - there is additional support needed to generate default values for nested structs and array valued fields. The work around for the moment is to use the `expr` attribute to control generation of values for complex fields (i.e array valued fields and struct valued fields)

3 - I'll add support in a series of successive PRs. The simplest level of support is to just generate `null` in cases where the field is array valued or struct valued which will avoid any issue with struct and array valued fields.  But as you point out, this by itself will not be very useful. 

I'm interested in feedback on what you would expect to be the default values for struct valued fields and can look at adding support in the early part of the coming quarter for it.

**Comment by ronanstokes-db** [comment]
Fixed - you can use either new or existing struct valued columns - but you must use `expr` to populate them
