### ISSUE TITLE
DBLDatagen broken on 14.3LTS Shared Cluster

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/dbldatagen#250]
DBR 14.3 LTS shared clusters use Spark Connect. There are apparently some unsupported references in the code base that break the generator on shared clusters.

To replicate, just try to generate data on 14.3LTS shared cluster.

![image](https://github.com/databrickslabs/dbldatagen/assets/10840635/c00e29a2-3b93-4986-ba22-f75b44fda637)

**Comment by ronanstokes-db** [comment]
PR to fix lack of sparkContext is https://github.com/databrickslabs/dbldatagen/pull/248

**Comment by ronanstokes-db** [comment]
Fixed in v0.3.6
