### ISSUE TITLE
Github pages for docs fails to load

### ISSUE THREAD

**Issue by zyd14** [databrickslabs/dbldatagen#265]
## Expected Behavior
The docs site https://databrickslabs.github.io/dbldatagen should load

## Current Behavior
I get the following using Firefox:
```

Secure Connection Failed

An error occurred during a connection to databrickslabs.github.io. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

## Steps to Reproduce (for bugs)
Try to go to https://databrickslabs.github.io/dbldatagen

## Context
Just trying to browse the docs with Firefox

## Your Environment

* `dbldatagen` version used: N/A
* Databricks Runtime version:  N/A
* Cloud environment used: N/A

**Comment by ronanstokes-db** [comment]
Can you clarify what browser etc you tried this with? 

I tried this from within a corporate VPN environment using Chrome, Safari on OSX, and from outside of a corporate VPN on Chrome and Edge on Windows, and Chrome and Safari on OSX

**Comment by ronanstokes-db** [comment]
I see in your earlier comment that you were using Firefox - apologies for the mistake. 

Anyway i downloaded Firefox 126.0 on Mac OSX and tried to download it and it worked. 

Are there specific security settings or aspects that you are using ?

**Comment by ronanstokes-db** [comment]
Could not reproduce
