### ISSUE TITLE
Doesn't work with Databricks Serverless Instances.

### ISSUE THREAD

**Issue by danielp-db** [databrickslabs/dbldatagen#295]
## Expected Behavior
DBLDATAGEN should be able to run with Databricks Serverless Instances as `spark.sql.execution.arrow.pyspark.enabled` is set by default.

## Current Behavior
Module fails as it checks for the value of the configuration.
![image](https://github.com/user-attachments/assets/8a9f43cd-afc2-4158-8a38-65493848187a)

## Steps to Reproduce (for bugs)
Connect a notebook to a Databricks Serverless Instance.
Import dbldatagen
Try creating a spec with DataGenerator.

## Context
N/A

## Your Environment
Databricks Serverless Instance

* `dbldatagen` version used: 0.4.0
* Databricks Runtime version:  Serverless
* Cloud environment used: Azure

**Comment by ronanstokes-db** [comment]
Thanks Daniel - this is a current open issue and will be in hotfix or next version

**Comment by ronanstokes-db** [comment]
See #292

**Comment by ronanstokes-db** [comment]
Fixed with most recent release
