### ISSUE TITLE
Add support for Spark 3.1.2 

### ISSUE THREAD

**Issue by ronanstokes-db** [databrickslabs/dbldatagen#91]
## Expected Behavior
Add explicit support for Spark 3.2 (included in Databricks runtime 9.1)

## Current Behavior
The current versions of the framework work in Databricks 9.1 (which is based on Spark 3.2). However there are some new features in Spark 3.2 that will tidy up syntax for some date and time constructs.

**Comment by alexott** [comment]
Technically speaking, DBR 9.1 is still based 3.1.2 with some backports from 3.2

**Comment by ronanstokes-db** [comment]
Will use feature compatibility of DBR 9.1 LTS as base line going forward which is based on 3.1.2

**Comment by ronanstokes-db** [comment]
Current release was upgraded to Spark 3.1.3
